export const CHANGE_SECTION = "CHANGE_SECTION";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const RENDER_MARKDOWN = "RENDER_MARKDOWN";
export const FILL_DOCS = "FILL_DOCS";
export const SEARCH_ITEM = " SEARCH_ITEM";
export const TOGGLE_SEARCH_RES = "TOGGLE_SEARCH_RES"
export const TOGGLE_SEARCH_RES_OFF = "TOGGLE_SEARCH_RES_OFF"
export const TOGGLE_SUB_SECTION = "TOGGLE_SUB_SECTION"